id_experiment: 0
repo: .
dataset_name: mnist
network_arch: resnet18
active_method: random 
initial_sample_size: 40000
query_size: 100
final_pool_size: 600  
attack: pgd 
batch_size: 128
epochs: 50
repeat: 1
seed: 60434
diversity: True
